version: '3'

networks:
    generic-network1:
      external:
        name: generic-network1

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - generic-network1
    stdin_open: true
    tty: true
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app  # Mount the current directory to /app in the container

  db:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - generic-network1
  adminer:
    image: adminer:4.7.6-standalone
    restart: always
    depends_on:
      - db
    container_name: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - generic-network1